import { ArrowRight, CircleQuestionMark } from "@stefan-florescu/icons";
import { Popover, PopoverTitle } from "@stefan-florescu/ui";

export default function PopoverDescription() {
  return (
    <div className="text-body flex items-center text-sm">
      This is just some informational text
      <Popover
        trigger="hover"
        placement="bottom-end"
        className="w-72 p-3"
        content={
          <div>
            <PopoverTitle className="mb-2 font-semibold">
              Activity growth - Incremental
            </PopoverTitle>
            <p className="mb-4">
              Report helps navigate cumulative growth of community activities. Ideally, the chart
              should have a growing trend, as stagnating chart signifies a significant decrease of
              community activity.
            </p>
            <h3 className="text-heading mb-2 font-semibold">Calculation</h3>
            <p className="mb-4">
              For each date bucket, the all-time volume of activities is calculated. This means that
              activities in period n contain all activities up to period n, plus the activities
              generated by your community in period.
            </p>
            <a
              href="#activity-growth"
              className="text-fg-brand flex items-center font-medium hover:underline"
            >
              Read more
              <ArrowRight aria-hidden className="ms-1 size-4 rtl:rotate-180" />
            </a>
          </div>
        }
      >
        <button
          type="button"
          className="text-body hover:text-heading focus-visible:outline-ring ms-2 rounded-full outline-hidden focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-solid"
        >
          <CircleQuestionMark aria-hidden className="size-4" />
          <span className="sr-only">Show information</span>
        </button>
      </Popover>
    </div>
  );
}
