/**
 * @stefan-florescu/icons — lucide.dev wrapper.
 *
 * Components must import icons from here, never from `lucide-react` directly, so
 * that size/stroke defaults, accessibility rules and the allowed icon set are
 * governed in one place. The visual spec (sizes, stroke width, optical
 * alignment) will be defined in a later phase.
 *
 * The allowed set is curated: add icons here (alphabetically) when a component
 * or the docs site needs them. Icons render with a 1.5 stroke (--sds-icon-stroke),
 * applied by @stefan-florescu/ui/styles.css.
 */
export type { LucideIcon, LucideProps } from "lucide-react";

export {
  ArrowLeft,
  ArrowRight,
  ArrowRightLeft,
  ArrowUp,
  ArrowUpRight,
  Atom,
  BadgePercent,
  Banknote,
  BedDouble,
  Bell,
  Bookmark,
  BookOpen,
  Calendar,
  CalendarPlus,
  ChartPie,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CirclePause,
  CircleQuestionMark,
  CircleUser,
  CircleX,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  CloudUpload,
  Columns3,
  Contact,
  Copy,
  CornerDownLeft,
  CreditCard,
  Database,
  DollarSign,
  Download,
  Ellipsis,
  EllipsisVertical,
  Eye,
  FileCode,
  FilePlus,
  FileText,
  Flame,
  Gift,
  GitBranch,
  Grid2x2Plus,
  Heart,
  House,
  Image,
  Inbox,
  Info,
  Layers,
  Link,
  ListOrdered,
  LoaderCircle,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  Maximize,
  Megaphone,
  Menu,
  MessageSquareText,
  Mic,
  Minus,
  Moon,
  Navigation2,
  Palette,
  Paperclip,
  Pause,
  Phone,
  Play,
  Plus,
  QrCode,
  RefreshCw,
  Rocket,
  Search,
  SendHorizontal,
  Server,
  Settings,
  Shield,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  SlidersVertical,
  Smile,
  SquareArrowOutUpRight,
  SquarePen,
  Star,
  Sun,
  Table,
  TextAlignCenter,
  TextAlignEnd,
  TextAlignJustify,
  TextAlignStart,
  Ticket,
  Trash2,
  TriangleAlert,
  Upload,
  User,
  UserMinus,
  UserPlus,
  Users,
  Video,
  Volume1,
  Volume2,
  Wallet,
  X,
} from "lucide-react";
