import { Check, X } from "@stefan-florescu/icons";
import report from "@stefan-florescu/themes/contrast.json";

type Result = { ratio: number; pass: boolean };
type Pair = {
  foreground: string;
  background: string;
  minimum: number;
  kind: string;
  results: Record<string, Result>;
};

const pairs = report as Pair[];
const themeNames = Object.keys(pairs[0]?.results ?? {});

function RatioCell({ result }: { result?: Result }) {
  if (!result) return null;
  return (
    <span className="inline-flex items-center gap-1.5 font-mono text-xs whitespace-nowrap">
      {result.pass ? (
        <Check aria-hidden className="text-success size-3.5" />
      ) : (
        <X aria-hidden className="text-danger size-3.5" />
      )}
      {result.ratio.toFixed(2)}:1
      <span className="sr-only">{result.pass ? "passes" : "fails"}</span>
    </span>
  );
}

/** WCAG contrast results for every checked pairing, generated by the themes build. */
export function ContrastTable() {
  return (
    <div className="my-6 w-full overflow-x-auto rounded-lg border">
      <table className="w-full min-w-[640px] text-sm">
        <caption className="sr-only">Contrast ratios of semantic colour pairings per theme</caption>
        <thead className="bg-surface">
          <tr className="border-b">
            <th scope="col" className="px-4 py-2 text-left font-medium">
              Foreground
            </th>
            <th scope="col" className="px-4 py-2 text-left font-medium">
              Background
            </th>
            <th scope="col" className="px-4 py-2 text-left font-medium">
              Minimum
            </th>
            {themeNames.map((theme) => (
              <th key={theme} scope="col" className="px-4 py-2 text-left font-medium capitalize">
                {theme}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {pairs.map((pair) => (
            <tr key={`${pair.foreground}-${pair.background}`} className="border-b last:border-b-0">
              <td className="px-4 py-2">
                <code className="font-mono text-xs">{pair.foreground}</code>
              </td>
              <td className="px-4 py-2">
                <code className="font-mono text-xs">{pair.background}</code>
              </td>
              <td className="px-4 py-2 font-mono text-xs whitespace-nowrap">
                {pair.minimum}:1 <span className="text-muted-foreground">({pair.kind})</span>
              </td>
              {themeNames.map((theme) => (
                <td key={theme} className="px-4 py-2">
                  <RatioCell result={pair.results[theme]} />
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
